return {
	'wbthomason/packer.nvim',
	'nvim-tree/nvim-tree.lua',
	'nvim-tree/nvim-web-devicons',
	'vim-test/vim-test',
	'tpope/vim-fugitive',
  	'tpope/vim-commentary',

  	-- rust babyyyyyyy
  	'mfussenegger/nvim-dap',
  	'rcarriga/nvim-dap-ui',
  	'simrat39/rust-tools.nvim',


  	'LunarVim/bigfile.nvim',
  	'tzachar/cmp-tabnine',
  	'metakirby5/codi.vim',
  	'monaqa/dial.nvim',
	"sindrets/diffview.nvim",
	'ruifm/gitlinker.nvim',
	'phaazon/hop.nvim',
	'tamago324/lir.nvim',
	'nvim-lua/plenary.nvim',
	'kyazdani42/nvim-web-devicons',
	'dccsillag/magma-nvim',
	'iamcco/markdown-preview.nvim',
	'karb94/neoscroll.nvim',
	'neovim/nvim-lspconfig',
	'tamago324/nlsp-settings.nvim',
	'williamboman/nvim-lsp-installer',
	'rcarriga/nvim-notify',
	'nacro90/numb.nvim',
	'kevinhwang91/nvim-bqf',
	'mfussenegger/nvim-jdtls',
	'folke/zen-mode.nvim',
	'mattn/webapi-vim',
	'andymass/vim-matchup',
	'mattn/vim-gist',
	'simrat39/symbols-outline.nvim',
	'Tastyep/structlog.nvim',
	'kevinhwang91/rnvimr',
	'unblevable/quick-scope',
	'nvim-treesitter/playground',
	'windwp/nvim-ts-autotag',
}