return {
	'wbthomason/packer.nvim',
	'nvim-tree/nvim-tree.lua',
	'nvim-tree/nvim-web-devicons',
	'vim-test/vim-test',
	'tpope/vim-fugitive',
  	'tpope/vim-commentary',

  	-- rust babyyyyyyy
  	'rcarriga/nvim-dap-ui',
  	'theHamsta/nvim-dap-virtual-text',
  	'simrat39/rust-tools.nvim',


  	'LunarVim/bigfile.nvim',
  	'metakirby5/codi.vim',
  	'monaqa/dial.nvim',
	'sindrets/diffview.nvim',
	'ruifm/gitlinker.nvim',
	'phaazon/hop.nvim',
	'tamago324/lir.nvim',
	'dccsillag/magma-nvim',
	'iamcco/markdown-preview.nvim',
	'karb94/neoscroll.nvim',
	'neovim/nvim-lspconfig',
	'tamago324/nlsp-settings.nvim',
	'williamboman/nvim-lsp-installer',
	'rcarriga/nvim-notify',
	'nacro90/numb.nvim',
	'kevinhwang91/nvim-bqf',
	'mfussenegger/nvim-jdtls',
	'folke/zen-mode.nvim',
	'mattn/webapi-vim',
	'andymass/vim-matchup',
	'simrat39/symbols-outline.nvim',
	'Tastyep/structlog.nvim',
	'kevinhwang91/rnvimr',
	'unblevable/quick-scope',
	'nvim-treesitter/playground',
	'windwp/nvim-ts-autotag',
	'nvim-telescope/telescope.nvim', 
	'nvim-lua/plenary.nvim',
	'hrsh7th/cmp-cmdline',
	'JoranHonig/tree-sitter-solidity',
	'tomlion/vim-solidity',
	'hrsh7th/nvim-cmp',
	'nvim-neotest/neotest-plenary',
	'folke/edgy.nvim',
	'echasnovski/mini.hipatterns',
}